export enum ApiErrorCode {
  AliasTaken = 'ALIAS_TAKEN',
  CreateLinkFailed = 'CREATE_LINK_FAILED',
  DatabaseNotConfigured = 'DATABASE_NOT_CONFIGURED',
  ImageRequired = 'IMAGE_REQUIRED',
  ImageTooLarge = 'IMAGE_TOO_LARGE',
  InvalidAlias = 'INVALID_ALIAS',
  InvalidImageType = 'INVALID_IMAGE_TYPE',
  InvalidUrl = 'INVALID_URL',
  PasswordTooLong = 'PASSWORD_TOO_LONG',
  PasswordTooShort = 'PASSWORD_TOO_SHORT',
  PreviewFetchFailed = 'PREVIEW_FETCH_FAILED',
  RateLimited = 'RATE_LIMITED',
  RedirectLimitExceeded = 'REDIRECT_LIMIT_EXCEEDED',
  StorageNotConfigured = 'STORAGE_NOT_CONFIGURED',
  UnreadablePreview = 'UNREADABLE_PREVIEW',
  UnsafeInternalUrl = 'UNSAFE_INTERNAL_URL',
  UnsupportedUrlProtocol = 'UNSUPPORTED_URL_PROTOCOL',
  UrlContainsCredentials = 'URL_CONTAINS_CREDENTIALS',
}
