export enum ApiErrorCode {
  AliasTaken = 'ALIAS_TAKEN',
  CreateLinkFailed = 'CREATE_LINK_FAILED',
  DatabaseNotConfigured = 'DATABASE_NOT_CONFIGURED',
  ImageRequired = 'IMAGE_REQUIRED',
  ImageTooLarge = 'IMAGE_TOO_LARGE',
  InvalidAlias = 'INVALID_ALIAS',
  InvalidImageType = 'INVALID_IMAGE_TYPE',
  InvalidUrl = 'INVALID_URL',
  PasswordTooLong = 'PASSWORD_TOO_LONG',
  PasswordTooShort = 'PASSWORD_TOO_SHORT',
  RateLimited = 'RATE_LIMITED',
  StorageNotConfigured = 'STORAGE_NOT_CONFIGURED',
  UnsupportedUrlProtocol = 'UNSUPPORTED_URL_PROTOCOL',
}
